export const FETCH_CONTACT_START = "FETCH_CONTACT_START";

export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";

export const FETCH_CONTACT_FAIL = "FETCH_CONTACT_FAIL";

export const SET_CONTACTS = "SET_CONTACTS";